### ISSUE TITLE
admin settings: Consider using @nextcloud/vue input components

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#11]
https://github.com/nextcloud/text2image_helper/blob/main/src/Components/AdminSettings.vue#L13

**Comment by MB-Finski** [comment]
Would AI be better? Or additional? Moved to ai for now.

**Comment by MB-Finski** [comment]
Done. NcSettingsInputText is unwieldy IMO so just used NcTextField, instead, since it allows for more customization and gets rid of the unnecessary submit button.
