### ISSUE TITLE
Unused code

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#12]
https://github.com/nextcloud/text2image_helper/blob/main/src/Components/AdminSettings.vue#L88

https://github.com/nextcloud/text2image_helper/blob/main/src/Components/AdminSettings.vue#L57

https://github.com/nextcloud/text2image_helper/blob/main/src/Components/AdminSettings.vue#L172

**Comment by MB-Finski** [comment]
Fixed in latest main.
