### ISSUE TITLE
Use proper l10n parameters

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#14]
https://github.com/nextcloud/text2image_helper/blob/main/src/Components/Text2ImageDisplay.vue#L32

This is not translatable by our system. See https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#javascript

**Comment by MB-Finski** [comment]
Fixed, thanks for the pointer to docs! I suspected that it wouldn't work but hadn't bothered checking yet.
