### ISSUE TITLE
Simplify Text2ImageHelperService#getImageDataFolder()

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#3]
https://github.com/nextcloud/text2image_helper/blob/main/lib/Service/Text2ImageHelperService.php#L158-L168

You can use appData->getFolder(...) inside a try-catch and then run createFolder in case getFolder fails. that avoids iterating over everything.

**Comment by MB-Finski** [comment]
That's true! For some reason, using try catch for general runtime logic felt a bit off. I'm really missing exists() here....

**Comment by marcelklehr** [comment]
you can use that method here as well to avoid duplication. https://github.com/nextcloud/text2image_helper/blob/main/lib/Service/CleanUpService.php#L52-L65

**Comment by MB-Finski** [comment]
Now the base service now uses geFolder() and the service method is used in the clean up sevice as suggested.
