### ISSUE TITLE
Use exceptions consistently in Text2ImageHelperService

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#4]
e.g. https://github.com/nextcloud/text2image_helper/blob/main/lib/Service/Text2ImageHelperService.php#L195

Any reason to not throw an exception here and in other places where you return `['error' => ... ]`? Would be more idiomatic I think. :)

**Comment by MB-Finski** [comment]
No particular reason other than copypasta from openAI integration.

**Comment by marcelklehr** [comment]
hah, oof

**Comment by MB-Finski** [comment]
Error now handling improved over several commits.
