### ISSUE TITLE
Nextcloud does not authenticate with localai when fetching generated images (probably)

### ISSUE THREAD

**Issue by mickenordin** [nextcloud/text2image_helper#49]
Steps to reproduce:

1. run local ai with basic auth.
2. Configure nextcloud integration_openai with your basic auth username and password
3.  Use smartpicker to generate image.
4. Image gets generated nicely, and can be accessed from localai (if autheniticated), but nextcloud gets 401:

```
nginx.1     | localai [22/Mar/2024:14:56:05 +0000] "POST /v1/images/generations HTTP/1.1" 200 242 "-" "Nextcloud OpenAI integration" "172.24.0.5:8080"
nginx.1     |  - [22/Mar/2024:14:56:05 +0000] "GET /generated-images/b64953982060.png HTTP/1.1" 401 179 "-" "Nextcloud Server Crawler" "-"
nginx.1     | localai [22/Mar/2024:14:56:22 +0000] "GET /generated-images/b64953982060.png HTTP/2.0" 200 68538 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0" "172.24.0.5:8080"
```

It seems to me that Nextcloud authenticates when asking for the image to be generated, but not when the image is ready, and should be fetched.

**Comment by julien-nc** [comment]
Thanks for the bug report.
This is related with the integration_openai app. See https://github.com/nextcloud/integration_openai/pull/84
