### ISSUE TITLE
Running multiple tasks in a loop instead of one task with n generations

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#6]
https://github.com/nextcloud/text2image_helper/blob/main/lib/Service/Text2ImageHelperService.php#L76

Here, you create n tasks. Instead we should create one task with the correct number of images set.

**Comment by MB-Finski** [comment]
Sure, this was written before it was implemented in the api.

**Comment by MB-Finski** [comment]
Multiple generations now uses the added api functionality.
