### ISSUE TITLE
Check user provided value in settings controller

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/text2image_helper#7]
https://github.com/nextcloud/text2image_helper/blob/main/lib/Controller/ConfigController.php#L35

Even if nothing should happen, we should check what comes in as data in that array to avoid storing stuff in the settings that we don't want/expect.

**Comment by MB-Finski** [comment]
Fixed in https://github.com/nextcloud/text2image_helper/commit/798165c44b302813087ed00bc15238c170ecc563
